apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-demo-deployment
  namespace: webapp-demo
  labels:
    app: webapp-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-demo
  template:
    metadata:
      labels:
        app: webapp-demo
    spec:
      containers:
      - name: webapp-demo
        image: hachemguetif/cicd:v1.18.1
        ports:
        - containerPort: 80