kind: Service
apiVersion: v1
metadata:
  name: webapp-demo
  namespace: webapp-demo
spec:
  selector:
    app: webapp-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer